# Experimental vars
exp_id: refactor_test
ds_remote_repo: deep-plants/AGM_HS
ds_local_repo: /workdir/cassava_disease/train
ds_save_to_local: false
stratify: true
result_dir: results
checkpoint_path: /workdir/baseline_species/results/resnet50_120_randaug_mixup/ckpts/model_60.pth
pretrain: agm
# Dataset vars
ds_mean: [0.36797073900515825, 0.4997646251138504, 0.26248408302026566]
ds_std: [0.18194517496156112, 0.20214607636275408, 0.17095115484747334]
img_size: [120, 120]
test: false
test_split: 0.2
validation_split: 0.2
fine_tune_on:  cassava
# Model vars
arch: resnet
patch_size: 8
only_cls_token: true
# FT vars
knn: false
n_neighbors: 5
svm: false
mlp_num_layers: 3
mlp_hidden_size: [192, 96]
blocks_to_optimize: "head" # ["head", "blocks.11"]
epochs: 11
cm_every_n: 5
batch_size: 32
learning_rate: 0.0001
use_weighted_loss: false
device: "cuda"