# Experimental vars
exp_id: EXP_id # Experiment ID
ds_remote_repo: deep-plants/AGM # Remote repo on HuggingFaceHub
ds_local_repo: /path/to/AGM # Local repo on the machine/path to save the dataset
ds_save_to_local: false # Save the dataset to local repo
stratify: true # Stratify the train/val/test splits or randomly generate the splits
result_dir: /path/to/results_dir
# Dataset vars
ds_mean: [0.36797073900515825, 0.4997646251138504, 0.26248408302026566]
ds_std: [0.18194517496156112, 0.20214607636275408, 0.17095115484747334]
img_size: [120, 120]
test_split: 0.2
validation_split: 0.2
transforms: "rot_and_flip" #  "default"(Normalization), "rot_and_flip"(Normalization + random rotation and flip), "full"(Normalization + Randaug + Mixup)
# Model vars
arch: vit_base # vit_small, resnet
patch_size: 8
save_every_n: 10
mlp_num_layers: 3 # Classification head MLP
mlp_hidden_size: [192, 96] # Last layer has dim equal to the number of classes
# Training vars
train: true
epochs: 101
batch_size: 240
learning_rate: 0.0001
use_weighted_loss: false
resume_training: false
checkpoint_path: null
device: "cuda"
cm_every_n: 2
opt_weight_decay: 0.00001